# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# Arduino IDE - force all windows/dialogs to open on active workspace
windowrule = match:class ^(arduino-ide)$, workspace unset
windowrule = match:class ^(arduino-ide)$, tag +projects
